name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Build
        env:
          PUBLIC_SITE_URL: https://fcedu.com.my
          PUBLIC_PLAUSIBLE_DOMAIN: fcedu.com.my
      - name: Setup service account file for Firestore export
        run: |
          echo "$GCP_SA_KEY_BASE64" | base64 -d > $RUNNER_TEMP/serviceAccount.json
        env:
          GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Export Firestore → JSON snapshots
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/serviceAccount.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: npm run data:pull
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
